### ISSUE TITLE
Scene Dataset Loading issue

### ISSUE THREAD

**Issue by cpotts-dwave** [dwave-examples/feature-selection-cqm#19]
When trying to load the app, I receive an error point towards the 'Scene' dataset. (see below) If I comment out all references to that dataset, I am able to load the 'Titanic' dataset and the app operates as normal. 

> Traceback (most recent call last):
  File "/workspace/feature-selection-cqm/app.py", line 45, in <module>
    datasets = {d['value']: DataSet(d['value']) for d in DATASET_NAMES}
  File "/workspace/feature-selection-cqm/app.py", line 45, in <dictcomp>
    datasets = {d['value']: DataSet(d['value']) for d in DATASET_NAMES}
  File "/workspace/feature-selection-cqm/data.py", line 167, in DataSet
    return datasets[name]()
  File "/workspace/feature-selection-cqm/data.py", line 141, in __init__
    dataset = openml.datasets.get_dataset(data_id)
  File "/workspace/.pip-modules/lib/python3.9/site-packages/openml/datasets/functions.py", line 432, in get_dataset
    parquet_file = _get_dataset_parquet(description)
  File "/workspace/.pip-modules/lib/python3.9/site-packages/openml/datasets/functions.py", line 1003, in _get_dataset_parquet
    openml._api_calls._download_minio_file(
  File "/workspace/.pip-modules/lib/python3.9/site-packages/openml/_api_calls.py", line 105, in _download_minio_file
    client.fget_object(
  File "/workspace/.pip-modules/lib/python3.9/site-packages/minio/api.py", line 1047, in fget_object
    stat = self.stat_object(
  File "/workspace/.pip-modules/lib/python3.9/site-packages/minio/api.py", line 1871, in stat_object
    response = self._execute(
  File "/workspace/.pip-modules/lib/python3.9/site-packages/minio/api.py", line 408, in _execute
    return self._url_open(
  File "/workspace/.pip-modules/lib/python3.9/site-packages/minio/api.py", line 373, in _url_open
    raise ServerError(
minio.error.ServerError: server failed with HTTP status code 503

**Comment by arcondello** [comment]
503 error implies to me that it may be transient. Can you let us know if it still persists say tomorrow?

**Comment by cpotts-dwave** [comment]
Some updates -- I tried again yesterday evening and the data loaded nicely, but when I tried again this morning I got a new set of errors. The issues are still only on the 'Scene' dataset, I was able to run the app on the 'Titanic' dataset by commenting out the references to the other dataset. 

> Leap IDE /workspace/feature-selection-cqm $ /usr/local/bin/python /workspace/feature-selection-cqm/app.py
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.9/site-packages/openml/datasets/dataset.py", line 491, in _cache_compressed_file_from_file
    data = pd.read_parquet(data_file)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 227, in read
    pa_table = self.api.parquet.read_table(
  File "/workspace/.pip-modules/lib/python3.9/site-packages/pyarrow/parquet/core.py", line 2939, in read_table
    dataset = _ParquetDatasetV2(
  File "/workspace/.pip-modules/lib/python3.9/site-packages/pyarrow/parquet/core.py", line 2479, in __init__
    [fragment], schema=schema or fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 1345, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/feature-selection-cqm/app.py", line 45, in <module>
    datasets = {d['value']: DataSet(d['value']) for d in DATASET_NAMES}
  File "/workspace/feature-selection-cqm/app.py", line 45, in <dictcomp>
    datasets = {d['value']: DataSet(d['value']) for d in DATASET_NAMES}
  File "/workspace/feature-selection-cqm/data.py", line 167, in DataSet
    return datasets[name]()
  File "/workspace/feature-selection-cqm/data.py", line 142, in __init__
    X, y, categorical_indicator, attribute_names = dataset.get_data(
  File "/workspace/.pip-modules/lib/python3.9/site-packages/openml/datasets/dataset.py", line 698, in get_data
    data, categorical, attribute_names = self._load_data()
  File "/workspace/.pip-modules/lib/python3.9/site-packages/openml/datasets/dataset.py", line 531, in _load_data
    return self._cache_compressed_file_from_file(file_to_load)
  File "/workspace/.pip-modules/lib/python3.9/site-packages/openml/datasets/dataset.py", line 493, in _cache_compressed_file_from_file
    raise Exception(f"File: {data_file}") from e
Exception: File: /home/gitpod/.cache/openml/org/openml/www/datasets/312/dataset.pq

**Comment by LoganLim2271** [comment]
I couldn't replicate the issue. It's working when I run it, even with the scene data. The error looks like the paraquet file is failing to be read because of the file signature. Possibly network connectivity issues causing the file to be corrupted? Would explain why the error is only happening sometimes.

**Comment by hbarovertwo** [comment]
Also unable to reproduce, but the latest traceback seems to indicate that the dataset stored in the cache (`/home/gitpod/.cache/openml/org/openml/www/datasets/312/dataset.pq`) is somehow corrupted. 

Line 141 of `data.py` calls `openml.datasets.get_dataset()` and passes the ID of the Scene dataset on OpenML. 
The docs for this method say that data will be loaded from the existing cache, if it exists. 

- Maybe try to clear the cache manually and re run?
- Or possibly do a run after editing Line 141 and passing the argument `force_refresh_cache = True` to the `get_dataset` call, this would clear the cache out. 

See docs here for reference:
https://openml.github.io/openml-python/develop/generated/openml.datasets.get_dataset.html

**Comment by cpotts-dwave** [comment]
That's fair... I was able to run the demo again today. I'll close the issue! Thanks for looking into it.
